#This configuration file for project
server:
    port: 444
    servlet:
        context-path: /banking2
        
spring:
    datasource:
        password: mysql@1234
        url: jdbc:mysql://localhost:3306/credit_store_db?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect